version: '3'

services:
  client:
    build: ./client
    image: bradyp123/docker_compose_1_client
    volumes: # Mount volumne cause error in k8s
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    build: ./server
    image: bradyp123/docker_compose_1_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - client