apiVersion: apps/v1
kind: Deployment
metadata:
  name: $JOB_NAME
  labels:
    app: busybox
spec:
  replicas: $NUM_TASKS
  selector:
    matchLabels:
      client: $JOB_NAME
  template:
    metadata:
      labels:
        client: $JOB_NAME
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
      # nodeSelector:
      #   name: $NODE

