apiVersion: batch/v1
kind: Job
metadata:
  name: $JOBID
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "$SLEEP_TIME"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: $NUM_CPU
      restartPolicy: Never
      nodeSelector:
        name: $NODE
  backoffLimit: 4