apiVersion: v1
kind: Pod
metadata:
  name: $JOBID
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: $NUM_CPU
    name: busybox
  nodeSelector:
    name: $NODE