apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "6"
      requests:
        cpu: "5"
  nodeSelector:
    name: caelum-201