apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        # command:
        # - sleep
        # - "30"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 5;done"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: $CPU
      restartPolicy: Never
  backoffLimit: 4