apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - image: bradyp123/docker_compose_1_server:latest
          name: server
          ports:
          - containerPort: 10001
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: server-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: server-hostpath0
status: {}
